# example netlify.toml
[build]
  command = "npm run build"
  # Base directory when deploying from GitHub
  base = "."
  functions = "netlify/functions"
  publish = ".next"

  # Map environment variables for build from Netlify settings
  [build.environment]
    NEXT_PUBLIC_SUPABASE_URL = "$NEXT_PUBLIC_SUPABASE_URL"
    NEXT_PUBLIC_SUPABASE_ANON_KEY = "$NEXT_PUBLIC_SUPABASE_ANON_KEY"
    NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY = "$NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY"
    GEMINI_API_KEY = "$GEMINI_API_KEY"
    STRIPE_SECRET_KEY = "$STRIPE_SECRET_KEY"
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"
    STRIPE_WEBHOOK_SECRET = "$STRIPE_WEBHOOK_SECRET"
    STRIPE_EFFECTO_RESTRICTED_KEY = "$STRIPE_EFFECTO_RESTRICTED_KEY"
    RATE_LIMIT_ENABLED = "$RATE_LIMIT_ENABLED"
    RATE_LIMIT_REDIS_URL = "$RATE_LIMIT_REDIS_URL"
    BILLING_EMAIL_FROM = "$BILLING_EMAIL_FROM"
    BILLING_EMAIL_SUPPORT = "$BILLING_EMAIL_SUPPORT"
    DEFAULT_CURRENCY = "$DEFAULT_CURRENCY"
    DEFAULT_BILLING_CYCLE = "$DEFAULT_BILLING_CYCLE"
    TRIAL_PERIOD_DAYS = "$TRIAL_PERIOD_DAYS"
    ENABLE_AI_FEATURES = "$ENABLE_AI_FEATURES"
    ENABLE_MEETING_SUMMARIES = "$ENABLE_MEETING_SUMMARIES"
    ENABLE_ADVANCED_ANALYTICS = "$ENABLE_ADVANCED_ANALYTICS"
    ENABLE_TEAM_COLLABORATION = "$ENABLE_TEAM_COLLABORATION"
    LOG_LEVEL = "info"
    ENABLE_PAYMENT_LOGGING = "$ENABLE_PAYMENT_LOGGING"
    ENABLE_USAGE_TRACKING = "$ENABLE_USAGE_TRACKING"

## Use Netlify's Next.js plugin to handle server functions and edge functions
[[plugins]]
  package = "@netlify/plugin-nextjs"

## Disable Netlify's local Neon DB emulator
## Disable Netlify's local Neon DB emulator and run Next.js dev server
[dev]
  enableLocalDb = false
  autoLaunch = false
  # Run Next.js dev on a different port to avoid conflicts
  command = "npm run dev -- -p 3001"
  
  # Explicitly provide Supabase env vars for Netlify Dev
  [dev.environment]
    NEXT_PUBLIC_SUPABASE_URL = "https://iyeoigedkksjghgwugzx.supabase.co"
    NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5ZW9pZ2Vka2tzamdoZ3d1Z3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNzE3MjIsImV4cCI6MjA2Nzg0NzcyMn0.0T8-XoUpuJ-H3WmgJqO8l86QQDyUwl2QOXHRy8XI3ds"

## Uncomment to use this redirect for Single Page Applications like create-react-app.
## Not needed for static site generators.
#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200

## (optional) Settings for Netlify Dev
## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
#[dev]
#  command = "yarn start" # Command to start your dev server
#  port = 3000 # Port that the dev server will be listening on
#  publish = "dist" # Folder with the static content for _redirect file

## more info on configuring this file: https://ntl.fyi/file-based-build-config
